import JSZip from 'jszip';

export async function exportDashboard(datasets, dashboard) {
  const zip = new JSZip();
  const dataFolder = zip.folder('data');

  for (const ds of datasets) {
    dataFolder.file(ds.name.endsWith('.csv') ? ds.name : ds.name + '.csv', toCSV(ds.data));
  }

  zip.file('dashboard.json', JSON.stringify({
    version: '1.0',
    dashboard,
    datasetMeta: datasets.map(d => ({ id: d.id, name: d.name })),
  }, null, 2));

  zip.file('README.md', generateMarkdown(dashboard));

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(dashboard.title || 'dashboard').replace(/[^a-z0-9]/gi, '_')}.ytics`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function importDashboard(file) {
  const zip = await JSZip.loadAsync(file);

  const cfgFile = zip.file('dashboard.json');
  if (!cfgFile) throw new Error('Invalid .ytics file: missing dashboard.json');

  const cfg = JSON.parse(await cfgFile.async('string'));
  const dataFolder = zip.folder('data');
  const datasets = [];

  for (const { id, name } of (cfg.datasetMeta || [])) {
    const fname = name.endsWith('.csv') ? name : name + '.csv';
    const f = dataFolder.file(fname);
    if (f) {
      const text = await f.async('string');
      const { data } = fromCSV(text);
      datasets.push({ id, name, data, originalData: data, transforms: [] });
    }
  }

  return { datasets, dashboard: cfg.dashboard };
}

function toCSV(data) {
  if (!data || !data.length) return '';
  const headers = Object.keys(data[0]);
  const escape = v => {
    if (v === null || v === undefined) return '';
    const s = String(v);
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"` : s;
  };
  return [
    headers.join(','),
    ...data.map(row => headers.map(h => escape(row[h])).join(',')),
  ].join('\n');
}

function fromCSV(text) {
  const lines = text.split('\n').filter(l => l.trim());
  if (lines.length < 2) return { data: [], columns: [] };
  const headers = parseCSVLine(lines[0]);
  const data = lines.slice(1).map(line => {
    const vals = parseCSVLine(line);
    const row = {};
    headers.forEach((h, i) => {
      const v = vals[i] ?? '';
      row[h] = v !== '' && !isNaN(v) ? Number(v) : v;
    });
    return row;
  });
  return { data, columns: headers };
}

function parseCSVLine(line) {
  const result = [];
  let cur = '';
  let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '"') {
      if (inQ && line[i + 1] === '"') { cur += '"'; i++; }
      else inQ = !inQ;
    } else if (c === ',' && !inQ) {
      result.push(cur); cur = '';
    } else {
      cur += c;
    }
  }
  result.push(cur);
  return result;
}

function generateMarkdown(dashboard) {
  let md = `# ${dashboard.title || 'Dashboard'}\n\n`;
  md += `> Generated by Ytics on ${new Date().toLocaleDateString()}\n\n`;
  if (dashboard.widgets?.length) {
    md += `## Visualizations\n\n`;
    for (const w of dashboard.widgets) {
      md += `### ${w.title || 'Untitled'}\n\n`;
      md += `| Property | Value |\n|---|---|\n`;
      md += `| Type | ${w.type} |\n`;
      if (w.xField) md += `| X Axis | ${w.xField} |\n`;
      if (w.yField) md += `| Y Axis | ${w.yField} |\n`;
      if (w.aggregation) md += `| Aggregation | ${w.aggregation} |\n`;
      if (w.colorField) md += `| Color | ${w.colorField} |\n`;
      md += '\n';
    }
  }
  return md;
}
